README.md

This is very much a matter of taste. But my UUoC reflex is strong and I found myself being distracted.

Avoid UUoC award

---

README.md

Document differences from Clojure

---

src/babashka/main.clj
test/babashka/main_test.clj

Was easy to add and quite powerful to have 
```
bb -e "(eval '(+ 1 2))"
3
```

Add clojure.core/eval

---

src/babashka/impl/clojure/stacktrace.clj
src/babashka/main.clj

Adds clojure.stacktrace to the available namespaces.

Add clojure.stacktrace

---

src/babashka/impl/clojure/core.clj

Adds Throwable->map to clojure.core

Add Throwable->map

---

README.md

Thanks for the awesome library!

Noticed a typo while trying an example

---

test/babashka/main_test.clj

Babashka follow up of https://github.com/borkdude/sci/pull/262

Add promise and deliver

---

doc/dev.md
src/babashka/impl/classes.clj
test/babashka/java_security_test.clj

I would like to calculate signatures of file contents in Babashka. This pull request add the Java classes needed to do this.
Another option would be to add functions that do the signatures themselves, but that might limit the number of use cases.

Add Security classes in order to be able to generate signatures

---

src/babashka/impl/clojure/core.clj

Turns out wanted to use file-seq :)

Support doc for file-seq

---

.github/workflows/deploy.yml
script/compile

Not sure if there is interest to use Github Actions, but here is something that can build for Linux and Mac.
I created it to verify another project, so no worries if it's not being used.
Example build: https://github.com/jeroenvandijk/babashka/runs/498935151?check_suite_focus=true

GitHub Actions build script

---

examples/whatsapp_counter.clj

I thought this was kinda fun, but, if it's not interesting enough as an example for this repo, dismiss this PR :-)

add whatsapp chat histogram example

---

examples/whatsapp_frequencies.clj

it's a taste thing, probably, dismiss if it conflicts with yours ;-)

tweak example by thread a bit more.

---

doc/libraries.md
script/lib_tests/clojure_data_zip_test
src/babashka/impl/clojure/zip.clj
src/babashka/main.clj

also adding library support, library test, and documentation for clojure.data.zip

adding support for clojure.zip

---

.circleci/config.yml
project.clj
script/postgresql_test
test-resources/babashka/embedded_pg_tests.clj
test/babashka/postgresql_test.clj

Embedded Postgres for tests on bb

---

README.md
doc/libraries.md

This should close the following tickets:
#434, #431, #430, #428, #426, #412, #383, #381

Update projects and other docs

---

README.md

There was a minor requested in here: #440
This PR resolves that

Changes as per request in PR #440

---

script/bump_graal_version.clj

This was also requested in #442

Add bump graal version script

---

doc/build.md
script/bump_graal_version.clj

Re: discussions in #babashka on Slack, I updated the version number to the build instructions.

Update GraalVM version in build instructions.

---

examples/http_server.clj

Resolve access to subfolder file errors( undo the indentation change)

Resolve access to subfolder file errors( undo the indentation change)

---

src/babashka/impl/classes.clj
src/babashka/impl/tools/cli.clj

Required for https://github.com/l3nz/cli-matic/pull/128
- Added more clojure.lang classes
- Added tools.cli/make-summary-part

Changes needed for cli-matic

---

script/compile

Compile script now follows symlinks when searching for svm.jar

---

README.md

sudo is required to move "$download_dir/bb" to "$PWD/bb"

add sudo to install command.

---

src/babashka/impl/classes.clj
test/babashka/main_test.clj
test/babashka/scripts/child.bb

See test/babashka/scripts/child.bb

Several improvements around destroying subprocesses

---

README.md

It's a small change but figured I'd get a PR in anyways. Let me know if you'd like me to change the format of the commit message!

Fixes changelog path in README.md

---

src/babashka/main.clj

Proof of concept for part of #543. The second case shows there is something off
```
echo "(defn f [_]
(/ 1 0))
(require '[spartan.spec :as s])
(s/explain (s/cat :x int? :y f) [1 #{:foo}])" > working.bb
lein bb -f working.bb
java.lang.Exception: Could not require spartan.spec. [at /Users/jeroen/Projects/Github/babashka/working.bb, line 3, column 3]
1: (defn f [_]
2:  (/ 1 0))
3:   (require '[spartan.spec :as s])
^--- Could not require spartan.spec. [at /Users/jeroen/Projects/Github/babashka/working.bb, line 3, column 3]
4: (s/explain (s/cat :x int? :y f) [1 #{:foo}]) nil
```
```
echo "(defn f [_]
(/ 1 0))
(/ a 2)
(require '[spartan.spec :as s])
(s/explain (s/cat :x int? :y f) [1 #{:foo}])" > not_working.bb
lein bb -f not_working.bb
clojure.lang.ExceptionInfo: Could not resolve symbol: a …
```

First try to add a more detailed error message

---

README.md
src/babashka/main.clj

Fix spelling error in `bb --help`

---

doc/libraries.md

Add in dharrigan/spotifyd-notification example.

Add in dharrigan/spotifyd-notification example

---

examples/image_viewer.clj

and don't error when the browser requests /favicon.ico

Let image_viewer example take options for port and dir

---

examples/README.md
examples/cprop-override.properties
examples/cprop.clj
examples/cprop.edn

Add basic usage for [tolitius/cprop](https://github.com/tolitius/cprop) library.

Add cprop example

---

README.md

Article about Passwordstore exporter w/ babashka [skip ci]

---

.circleci/config.yml
.github/workflows/build.yml
Dockerfile
appveyor.yml
doc/build.md
doc/dev.md
project.clj
script/bump_graal_version.clj
script/compile
script/compile.bat

Update GraalVM to 21.0.0

---

src/babashka/impl/classes.clj
src/babashka/impl/reify.clj
src/babashka/main.clj

Using this I can have complete custom `MapEntry` implementation!

Add IndexOutOfBoundsException, IHashEq and Map$Entry

---

README.md

Document install new flags in README.md

---

src/babashka/main.clj

Use sequential? for identifying if the script output needs splitting

---

src/babashka/impl/error_handler.clj
test/babashka/error_test.clj

I hope I won't step on anyone's feet, but I have written the two lines of code for #730. Is there anything else needed for this issue?

feat: print data of uncaught ExceptionInfo to output

---

src/babashka/impl/classes.clj
test/babashka/main_test.clj

[#872] Add java.lang.ProcessHandle$Info 

---

test/babashka/main_test.clj

In the spirit of starting small, this change just adds the windows selector to a few tests that pass with no other changes needed.

add windows selector to a couple of tests (#235)

---

examples/README.md
examples/xml-example.clj

- checking stdin for available input
- using data.xml lib
the XML example uses a contrived XML doc, but I thought that might be nice from a "fits in my head" perspective

add examples for #324 and #369 [skip ci]

---

deps.edn
test-resources/lib_tests/babashka/run_all_libtests.clj
test-resources/lib_tests/omniconf/core_test.clj

this is the first thing I've added to lib tests, so please feel free to tell me the things I got wrong :)

add omniconf lib test (#877)

---

appveyor.yml
script/lib_tests/run_all_libtests.bat
script/run_lib_tests.bat
test-resources/lib_tests/babashka/run_all_libtests.clj
test-resources/lib_tests/clojure/data/json_test.clj
test-resources/lib_tests/selmer/core_test.clj

From my local testing, it seems like the environment setup should be ok, but we'll see what Appveyor makes of it. :)
The change in the selmer test is due to what feels like a very esoteric issue with the URL paths for resources - I figure the testing is nicer to have, and then I'll look deeper into the issue once the tests are setup.

run lib tests in Windows CI

---

test/babashka/deps_test.clj

This should address the skipped test in #936 - it's definitely not as pretty as using `pr-str`, but I haven't been able to get a `pr-str` working on Windows (native) because of the differences between Windows shell escaping and Clojure escaping. I will not be offended if you want to reject the code based purely on the relative ugliness of the string manipulation. :)

add windows-specific babashka.deps-test/clojure-test (#936)

---

src/babashka/main.clj
test/babashka/main_test.clj

I assume this is what you had in mind for #729

make the REPL requires available to command-line scripts (closes #729)

---

test/babashka/java_http_client_test.clj

Confirming we see the expected exceptions.

Add cert tests expired, wrong-host, and self-signed certs.

---

src/babashka/impl/classes.clj

Adds java.util.zip.ZipFile to classes exposed by Babashka. ZipFile has some utilities that might be useful :)

Add ZipFile

---

deps.edn
doc/projects.md
examples/README.md
examples/memo.clj
test-resources/lib_tests/babashka/run_all_libtests.clj
test-resources/lib_tests/component/component_test.clj

Closes #742 and #451 
- add a lib test for component
- add component to the libraries list
- add an example of using gzip streams to the examples page

Component lib test

---

src/babashka/impl/error_handler.clj
test/babashka/error_test.clj

Closes #1015 
The issue title says "consider", so I don't know if you definitely want this.

print locals only when debug option is enabled (#1015)

---

doc/projects.md
examples/README.md
examples/db_who.clj

- closes #396 
- closes #486 
adds example and doc based on issue descriptions

add mysql pprint example and minimallist doc [skip ci]

---

src/babashka/impl/classes.clj

Add clojure.lang.IPersistentList

---

src/babashka/impl/classes.clj

add JarInputStream

---

script/compile

fix script/compile #1089

---

.dockerignore

These can leak host env stuff into Docker build context and break things

Add .cpcache and target to .dockerignore

---

.github/pull_request_template.md
install

Fix issue https://github.com/babashka/babashka/issues/1107.

Check shasum/sha256sum in PATH on install script

---

deps.edn
doc/projects.md
test-resources/lib_tests/babashka/run_all_libtests.clj
test-resources/lib_tests/com/stuartsierra/dependency_test.clj
test-resources/lib_tests/reifyhealth/specmonstah/core_test.cljc

Hi @borkdude. I've added tests for 2 libraries. It may be nice to automate this one day. I could give this a shot next time I add a library
- [-] I have updated the [CHANGELOG.md](https://github.com/babashka/babashka/blob/master/CHANGELOG.md) file with a description of the addressed issue.
I haven't only b/c I don't think we do this for tested libraries.

Added specmonstah and dependency to tested libraries

---

deps.edn
doc/dev.md
script/add-libtest.clj
test-resources/lib_tests/again/core_test.clj
test-resources/lib_tests/arrangement/core_test.cljc
test-resources/lib_tests/babashka/run_all_libtests.clj
test-resources/lib_tests/bb-tested-libs.edn
test-resources/lib_tests/clojure/tools/gitlibs/test_impl.clj
test-resources/lib_tests/clojure/tools/test_gitlibs.clj
test-resources/lib_tests/clojure_csv/test/core.clj
test-resources/lib_tests/clojure_csv/test/utils.clj
test-resources/lib_tests/comb/test/template.clj

Hi @borkdude. I followed up on my comment on #1109 and added a script to make testing new libraries easy. There's an example in the documentation. With this script I added two new libraries and added tests for 3 existing libraries. I did have to make a couple minor fixes and they are noted with a "TEST-FIX" comment.
While trying to add tests for data.zip I encountered that `clojure.xml` which ships with clojure doesn't exist. It may be worth porting at some point. You can reproduce the failure with `script/add-libtest.clj '{org.clojure/data.zip {:mvn/version "1.0.0"}}' https://github.com/clojure/data.zip --test`
Cheers
- [-] I have updated the [CHANGELOG.md](https://github.com/babashka/babashka/blob/master/CHA …

Add libtest

---

doc/news.md

fix typo in news

---

.circleci/script/docker
CHANGELOG.md

Build alpine Docker images in CI when linux/amd64 is in platform list

---

deps.edn
doc/libraries.csv
script/add-libtest.clj
test-resources/lib_tests/bb-tested-libs.edn
test-resources/lib_tests/clj_stacktrace/core_test.clj
test-resources/lib_tests/clj_stacktrace/repl_test.clj
test-resources/lib_tests/datalog/parser/impl_test.cljc
test-resources/lib_tests/datalog/parser/pull_test.cljc
test-resources/lib_tests/datalog/parser/test/util.cljc
test-resources/lib_tests/datalog/parser_test.cljc
test-resources/lib_tests/datalog/unparser_test.clj

Hi. Thanks! for fixing #1170. I confirmed datalog-parser works nicely for what I'm doing. Added it and another lib I noticed was compatible
---
- [-] I have updated the [CHANGELOG.md](https://github.com/babashka/babashka/blob/master/CHANGELOG.md) file with a description of the addressed issue.

Add 2 more compatible libs

---

doc/projects.md

minor typo

---

src/babashka/impl/pprint.clj

pprint: add get-pretty-writer

---

CHANGELOG.md
src/babashka/impl/classes.clj
src/babashka/impl/proxy.clj
test/babashka/proxy_test.clj

Spire requires proxy support for java.io.PipedInputStream and java.io.PipedOutputStream

---

resources/META-INF/babashka/deps.edn
src/babashka/impl/classpath.clj
src/babashka/impl/pods.clj
src/babashka/main.clj
test/babashka/uberjar_test.clj

Feature: declarative pods support in uberjars

---

deps.edn
doc/libraries.csv
doc/projects.md
test-resources/lib_tests/bb-tested-libs.edn
test-resources/lib_tests/clarktown/core.md
test-resources/lib_tests/clarktown/core_result.html
test-resources/lib_tests/clarktown/core_test.clj
test-resources/lib_tests/clarktown/parsers/bold_test.clj
test-resources/lib_tests/clarktown/parsers/code_block.md
test-resources/lib_tests/clarktown/parsers/code_block_no_language.md
test-resources/lib_tests/clarktown/parsers/code_block_no_language_result.html
test-resources/lib_tests/clarktown/parsers/code_block_result.html
test-resources/lib_tests/clarktown/parsers/code_block_test.clj
test-resources/lib_tests/clarktown/parsers/empty_block_test.clj
test-resources/lib_tests/clarktown/parsers/heading_block_test.clj
test-resources/lib_tests/clarktown/parsers/horizontal_line_block_test.clj
test-resources/lib_tests/clarktown/parsers/inline_code_test.clj
test-resources/lib_tests/clarktown/parsers/italic_test.clj
test-resources/lib_tests/clarktown/parsers/link_and_image_test.clj
test-resources/lib_tests/clarktown/parsers/quote_block_test.clj
test-resources/lib_tests/clarktown/parsers/strikethrough_test.clj

closes #1234 
the tests use some resource files, so files were copied and paths were changed - these are marked with BB-TEST-PATCH, along with a line separator patch.

add Clarktown lib tests

---

resources/META-INF/babashka/deps.edn
src/babashka/impl/classes.clj
src/babashka/impl/pprint.clj

Some additions that at least make plumatic/schema run partially

---

README.md

Add installation instructions using nix

---

CHANGELOG.md
src/babashka/impl/nrepl_server.clj
src/babashka/main.clj

This change exposes babashka.nrepl.server-functions for programmatic use
Solves #1295 
---

Exposing babashka.nrepl.server-functions

---

doc/projects.md

---
Adding the `bb-github-app` a nice possibility to write Github applications using nothing but Babashka 😄

add bb-github-app project

---

README.md

README: Add link to babashka.org from logo

---

CHANGELOG.md
src/babashka/impl/classes.clj

Add exception classes useful for clj-http-lite

---

src/babashka/impl/server.clj

I did compile `bb` and tried `stop-server` and it seems to work OK.

Add clojure.core.server/stop-server

---

resources/META-INF/babashka/deps.edn
src/babashka/impl/classes.clj

Add more reflection classes

---

README.md
examples/README.md
examples/wiki-translate.clj

- add wikipedia translation example (closes #595 )
- change readme example to unsetting environment variables (closes #639 )
- add URL to "Breakneck Babashka on K8s"
- add missing entry to examples TOC
- change 'file-server.clj' to 'http-server.clj' to fix link
I suspect the 'skip CI' thing won't work, but it shouldn't hurt to try.

doc additions/cleanups [skip ci]

---

install

Fix small typo

---

.circleci/script/short_ci.clj
.cirrus.yml
.github/workflows/build.yml
Dockerfile
appveyor.yml
doc/build.md
doc/dev.md
script/bump_graal_version.clj
test/babashka/crypto_test.clj

Graalvm 22.3.0

---

CHANGELOG.md
deps.edn
doc/libraries.csv
doc/projects.md
test-resources/lib_tests/bb-tested-libs.edn

Sluj tests

---

examples/normalize-keywords.clj

make normalize-keywords walk clj[cdx]? files in specified location

---

examples/normalize-keywords.clj

allow normalize-keywords to work on cljs files

---

CHANGELOG.md
doc/nix.md

https://github.com/Sohalt/write-babashka-application-example/commit/e24cd9e085aa7432bdda6cd4b55bdd3af8ef3f48

refactor: propose changing to working example found at

---

CHANGELOG.md
README.md

Add note about BSOD when using WSL1

---

CHANGELOG.md
feature-httpkit-client/babashka/impl/httpkit_client.clj
test-resources/lib_tests/httpkit/client_test.clj

Closes #1438 
Basically just a couple copy-vars and a couple smoke tests.

#1438: httpkit.client functions

---

Dockerfile
script/setup-musl

Update zlib to version 1.2.13

---

src/babashka/impl/clojure/test.clj
test/babashka/test_test.clj

Allow passing explicit file and line number to clojure.test (#1451)

---

.circleci/config.yml
.circleci/script/gen_ci.clj
.circleci/script/short_ci.clj
script/check_glibc.sh

with a heavy heart, wrote this in bash. setting up `bbb` at this depth seems too much work?

Add check for max glibc version

---

CHANGELOG.md
src/babashka/impl/classes.clj

Add java.util.jar.Attributes to classes

---

src/babashka/impl/classpath.clj

Fixes https://github.com/babashka/babashka/issues/1474

Use UrlClassLoader for finding files on classpath

---

CHANGELOG.md
src/babashka/impl/deps.clj
test/babashka/bb_edn_test.clj
test/babashka/test_utils.clj

[#1473] Make deps resolve paths relative to bb.edn

---

CHANGELOG.md
deps.edn
doc/libraries.csv
test-resources/lib_tests/bb-tested-libs.edn

Closes #1000 
Tests work with no patches needed, so this is just a "pull the tests from the git lib and execute them" addition.
---

add lib tests for xforms

---

doc/companies.md

Added Kleene to companies

---

CHANGELOG.md
project.clj
src/babashka/impl/classes.clj
test/babashka/interop_test.clj

Addresses https://github.com/babashka/babashka/issues/1507

Vthread methods

---

.circleci/script/docker.clj
.circleci/script/gen_ci.clj
CHANGELOG.md

[#1521] Push images to GHCR

---

.circleci/script/gen_ci.clj
CHANGELOG.md

No liunx aarch64 dynamic builds

---

.circleci/script/docker.clj
.circleci/script/gen_ci.clj

[#1524] fix docker orchestration

---

test-resources/lib_tests/babashka/run_all_libtests.clj

Now that babashka.process tests are os agnostic we can also run them on Windows.

tests: run babashka.process lib tests on windows

---

CHANGELOG.md
src/babashka/impl/clojure/java/browse.clj
test/babashka/impl/clojure/java/browse_test.clj

Escape URLs for clojure.java.browse/browse-url on Windows

---

README.md

Straight out recommending Babashka Babooka, instead of conditioning the recommendation on that the user has read Clojure for the Brave and True. Also adding some little info about Daniel.

Tweak Babashka Babooka copy

---

.circleci/script/gen_ci.clj

See https://github.com/babashka/babashka/issues/1598

Use macos.x86.medium.gen2 resource

---

CHANGELOG.md
src/babashka/impl/classes.clj

Support clojure.lang.LongRange

---

deps.edn
project.clj
resources/META-INF/babashka/deps.edn

bump cheshire

---

CHANGELOG.md
feature-yaml/babashka/impl/ordered.clj
src/babashka/impl/classes.clj
src/babashka/main.clj
test-resources/pod.clj
test/babashka/main_test.clj

Closes #1692.
I am not able to run the tests locally (I get NPEs in `babashka.main/fn`), so my apologies if this is broken. I don't know enough about Babashka to solve the tests issue.

Add ITransientSet and flatland.ordered-set

---

CHANGELOG.md
deps.edn
project.clj
resources/META-INF/babashka/deps.edn

Follow-up to #1693. Safe to upgrade after https://github.com/clj-commons/ordered/commit/dd4bfd028556e5717f8d793050597f8e217ec5ea which was included in 1.15.11.

Update org.flatland/ordered to 1.15.12

---

doc/dev.md

Some extra notes for Windows that I expect will benefit others and also future-me!

docs: dev: windows tips

---

Dockerfile

Fixes #1731 
----
_Nope, it's preliminary -- I am trying to fix #1728_
_Not yet but I think it would be good to ensure that the Dockerfile actually works._
_Happy to add that if you see the need for it._

Dockerfile nitpicks

---

CHANGELOG.md
src/babashka/impl/classes.clj
test/babashka/interop_test.clj

- [ x ] I have read the [developer documentation](https://github.com/babashka/babashka/blob/master/doc/dev.md).
- [x ] This PR corresponds to an [issue with a clear problem statement](https://github.com/babashka/babashka/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).
- [ x ] This PR contains a [test](https://github.com/babashka/babashka/blob/master/doc/dev.md#tests) to prevent against future regressions
- [x ] I have updated the [CHANGELOG.md](https://github.com/babashka/babashka/blob/master/CHANGELOG.md) file with a description of the addressed issue.

Add RT iter to babashka

---

CHANGELOG.md
src/babashka/impl/classes.clj

...to support com.gfredericks/test.chuck library
- [N/A] This PR contains a [test](https://github.com/babashka/babashka/blob/master/doc/dev.md#tests) to prevent against future regressions

Add java.util.regex.PatternSyntaxException

---

CHANGELOG.md
feature-logging/babashka/impl/logging.clj
resources/META-INF/babashka/deps.edn
test-resources/lib_tests/babashka/statecharts_test.clj

Co-authored-by: sheluchin <alex.sheluchin@gmail.com>

Statechart tests

---

CHANGELOG.md
src/babashka/impl/classes.clj

feat: add clojure.lang.ITransientCollection for instance? checks
