babashka/babashka

README.md, src/babashka/main.clj, test/babashka/main_test.clj
When an argument is a file name (i.e. the file exists), then treat it as a file,
rather than as an expression.
Update dev docs.
Closes #59
=> Add an -e/--eval option, and automatically detect file name args

src/babashka/impl/Boolean.clj, src/babashka/impl/Double.clj, src/babashka/main.clj
Added:
* Double/parseDouble
* Boolean/parseBoolean
I need this for a project where I parse command-line options with these types. I figured `Float/parseFloat` is redundant because of the implicit cast of Float to Double.
Note that I wasn't able to run the tests:
```
script/test
Syntax error (FileNotFoundException) compiling at (babashka/impl/socket_repl.clj:1:1).
Could not locate sci/impl/interpreter__init.class, sci/impl/interpreter.clj or sci/impl/interpreter.cljc on classpath.
Full report at:
/var/folders/ck/9zqvs0zx5vsf2bc7rvv1pwc40000gn/T/clojure-2853884920458488806.edn
Tests failed.
```
I've basically copied the `Integer.clj` namespace and adapted it to my best knowledge.
=> Added more String parsers

reflection.json, src/babashka/impl/classes.clj
Needed in order to work with file attributes that include times.
```
user=> (-> (File. "src") .toPath (java.nio.file.Files/readAttributes "*" (make-array java.nio.file.LinkOption 0)) (get "lastModifiedTime"))
#object[java.nio.file.attribute.FileTime 0x52e0cdac "2020-01-01T23:34:20Z"]
user=> (-> (File. "src") .toPath (java.nio.file.Files/readAttributes "*" (make-array java.nio.file.LinkOption 0)) (get "lastModifiedTime") .toInstant)
#object[java.time.Instant 0x29d3a09e "2020-01-01T23:34:20Z"]
user=> (-> (File. "src") .toPath (java.nio.file.Files/readAttributes "*" (make-array java.nio.file.LinkOption 0)) (get "lastModifiedTime") (.to java.util.concurrent.TimeUnit/NANOSECONDS))
1577921660000000000
```
=> Add FileTime and TimeUnit for working with times on file attributes

Dockerfile
I find that one has to jump through a lot of hoop in order to get glibc and/or libstdc++ working on Alpine. It might be easier to use a popular base image which everyone probably has it in the local cache.
Related:
* https://github.com/sgerrand/alpine-pkg-glibc/issues/80
* https://gitlab.alpinelinux.org/alpine/aports/issues/4903
Fix #259
=> Using ubuntu:bionic

README.md, src/babashka/main.clj
AWS Lambda doesn't support signal [handling](https://github.com/oracle/graal/issues/841), e.g. [here](https://github.com/quarkusio/quarkus/issues/4262). Therefore, in order for babashka to work, it is needed to disable the handling of SIGPIPE.
I propose to introduce an environment variable to alter the default behaviour and disable the handling of SIGPIPE: `BABASHKA_DISABLE_PIPE_HANDLER`. 
An example project that runs babashka script in AWS Lambda https://github.com/dainiusjocas/babashka-lambda.
=> Support AWS Lambda custom runtime

README.md
I found the examples using aliases hard to understand and didn't want to spin up an entire clojure instance to calculate the classpath.
Feel free to do with it as you want.
=> Added an example about using deps.clj script to produce the classpath

README.md
The example in the README for using medley is missing the `/medley` project at the end of the git URL.
Tested the updated example with current `bb`:
```
BABASHKA_CLASSPATH=$(clojure -Spath -Sdeps '{:deps {medley {:git/url "https://github.com/weavejester/medley" :sha "a4e5fb5383f5c0d83cb2d005181a35b76d8a136d"}}}') bb
Cloning: https://github.com/weavejester/medley
Checking out: https://github.com/weavejester/medley at a4e5fb5383f5c0d83cb2d005181a35b76d8a136d
Babashka v0.0.80 REPL.
Use :repl/quit or :repl/exit to quit the REPL.
Clojure rocks, Bash reaches.
user=>
```
=> correct medley deps in README

src/babashka/impl/nrepl_server.clj
This new implementation is faster because you only flush when you issue `.flush`, or until the buffer is full. Some simple experiments with Chlorine confirmed that small messages are being received in a whole block, instead of fragmented.
=> Send bencode using BufferedOutputStream

doc/projects.md
Saw the issue so figured I'd add it :) It could be useful to make a distinction in that document between projects that use babashka and libraries that are compatible with babashka
=> Add my project - close #392

src/babashka/impl/classes.clj
I'd like to `bb '(Float/parseFloat "7.5")'` and was unable to. I think this is all that is needed to enable this. Cheers
=> Add Float class for use in scripts

README.md, src/babashka/impl/pipe_signal_handler.clj, src/babashka/impl/sigint_handler.clj
The introduction of shutdown hooks from v0.0.81 prevents babashka from running in an AWS lambda. This PR allows disabling the hook through the same env var for disabling the pipe signal handler and renames the env variable for simplicity.
=> Disable signal handlers on AWS lambdas via env var

script/lib_tests/clojure_data_generators_test, script/run_lib_tests, src/babashka/impl/classes.clj, src/babashka/main.clj, test-resources/lib_tests/clojure/data/generators_test.clj
I would like to use `clojure.data.generators` in a babashka script to deterministically generate data.
These changes are required to load `clojure.data.generators`: 
```
bb -e '(eval (read-string (str "(do" (slurp "https://raw.githubusercontent.com/clojure/data.generators/master/src/main/clojure/clojure/data/generators.clj")
```
This adds the missing classes `java.util.Random` and `java.lang.Short`
This adds the missing aliases `BigInteger` and `Short`
`double-array` and `short-array` are added via https://github.com/borkdude/sci/pull/350
I didn't add unit tests as I'm not sure what a good test would be other than loading the generator namespace.
=> Add support for clojure.data.generators

src/babashka/impl/clojure/java/browse.clj, src/babashka/main.clj
Fixes #495. 
cc @lread
One issue remains to be fixed on Windows:
```
C:\Users\borkdude\Downloads>bb -e "(require '[clojure.java.browse :refer [browse-url]]) (browse-url \"https://babashka.org\")"
java.io.IOException: Cannot run program "start": CreateProcess error=2, The system cannot find the file specified [at line 1, column 54]
```
This seems to work:
```
> bb -e "(require '[clojure.java.shell :refer [sh]]) (sh \"cmd.exe\" \"/C\" \"start\" \"https://babashka.org\")"
{:exit 0, :out "", :err ""}
```
=> [#495] add clojure.java.browse/browse-url

README.md
Some text added to README to clarify non-printing of returned nil values
=> Describe non-printing of returned nil

src/babashka/impl/classes.clj
Hi borkdude. I'd like to be able to use https://github.com/circleci/bond for a bb testing tool I'm writing. Is this ok? I don't know the guidelines on what classes are ok to add but I figured anything with clojure.* was fair game. 
I'm happy to add bond to libraries.md and lib_tests/. Does one just create a new directory in test-resources/lib_tests/ and copy over tests from the library?
Cheers
=> Add java class to support circle/bond

deps.edn, doc/dev.md, doc/libraries.md, test-resources/lib_tests/babashka/run_all_libtests.clj, test-resources/lib_tests/bond/test/assertions.cljc, test-resources/lib_tests/bond/test/james.cljc, test-resources/lib_tests/bond/test/target.cljc
Hi borkdude.
I'm following up on #522 to add tests for bond. There is one issue. Currently a [test fails](https://github.com/cldwalker/babashka/blob/39dd76cc2e882e35f6909dfe295a2e1ed7127ddb/test-resources/lib_tests/bond/test/james.cljc#L9-L19) because bb behaves differently than clojure. When a fn is called with an incorrect number of arguments, bb throws Exception whereas clojure throws clojure.lang.ArityException. Would it be ok to change bb to match clojure's behavior? I can attempt this change in sci if you'd like
Cheers
=> Add lib tests for bond

doc/repl.md
In the suggested helper script for starting the nrepl server, set the classpath to include `src` and `test` dirs, so that :require works correctly when the script is run from the project root.
```
;; <skipped>
(let [nrepl-port (with-open [sock (ServerSocket. 0)] (.getLocalPort sock))
cp (str/join File/pathSeparatorChar ["src" "test"])
pb (doto (ProcessBuilder. (into ["bb" "--nrepl-server" (str nrepl-port)
"--classpath" cp]
*command-line-args*))
(.redirectOutput ProcessBuilder$Redirect/INHERIT))
proc (.start pb)]
(wait/wait-for-port "localhost" nrepl-port)
(spit ".nrepl-port" nrepl-port)
(.deleteOnExit (File. ".nrepl-port"))
(.waitFor proc))
```
=> [doc] set classpath in the nrepl helper script

doc/libraries.md
The `use` syntax relies on resolution of #565
=> Document version-clj as a library that works with babashka

deps.edn, test-resources/lib_tests/babashka/run_all_libtests.clj, test-resources/lib_tests/version_clj/compare_test.cljc, test-resources/lib_tests/version_clj/core_test.cljc, test-resources/lib_tests/version_clj/split_test.cljc, test-resources/lib_tests/version_clj/via_use_test.clj
The version-clj project uses `.cljx` so I hand-transcribed them to `.cljc`.
Tests are from from version-clj v1.0.2:
https://github.com/xsc/version-clj/tree/clojars-0.1.2
Added `version-clj.via-use-test` to verify loading version-clj via `use`.
Verification via: `./script/run_lib_tests`, I observed version-clj tests:
1. failing for `bb` native v0.2.0
2. passing for `./bb` native built from master
3. passing for `lein bb` from master
This should be the final change that closes #565.
=> Added lib tests for version-clj

install
Install the custom version or latest version of babashka using command line args
=> Adding the custom version support in command line args

doc/build.md, feature-lanterna/babashka/impl/lanterna.clj, project.clj, script/uberjar, script/uberjar.bat, src/babashka/impl/features.clj, src/babashka/main.clj
When compiling with the env variable `BABASHKA_FEATURE_LANTERNA=true` the following Babashka script can be run, which will start a TUI instance with text.
```clojure
(require '[lanterna.terminal :as terminal])
(def terminal (terminal/text-terminal))
(terminal/start terminal)
(terminal/put-string terminal "Hello TUI Babashka!" 10 5)
(terminal/flush terminal)
(Thread/sleep 1000)
```
=> Add clojure-lanterna

Dockerfile
With the current Ubuntu based docker image it is not possible to use
babashka.curl:
```
> docker run --rm -it borkdude/babashka:0.2.3-SNAPSHOT bb '(-> "https://httpstat.us/200" babashka.curl/get :status)'
----- Error --------------------------------------------------------------------
Type:     java.io.IOException
Message:  Cannot run program "curl": error=2, No such file or directory
Location: <expr>:1:1
----- Context ------------------------------------------------------------------
1: (-> "https://httpstat.us/200" babashka.curl/get :status)
^--- Cannot run program "curl": error=2, No such file or directory
----- Stack trace --------------------------------------------------------------
babashka.curl/get - <built-in>
user              - <expr>:1:1
```
After this change it works:
```
> …
```
=> Docker image: Install curl to support babashka.curl

.gitignore, doc/build.md, project.clj, script/compile, script/uberjar, script/uberjar.bat, src/babashka/impl/features.clj, src/babashka/main.clj
NOTE: Using the Oracle driver directly requires some GraalVM settings
while the helidon wrapper provides those and thus works out of the box.
=> Add feature/oracledb

src/babashka/impl/classes.clj, test/babashka/java_io_piped_stream_test.clj
I have use-case that required `java.io.PipedInputStream` and `java.io.PipedOutputStream` in code which is missing from Babashka.
This PR attempt to add these two classes to Babashka.
=> Add the missing class from java.io

examples/README.md, examples/rofi.clj
The fzf example inspired me to share [rofi](https://github.com/davatorium/rofi) as a similar use-case - I've leaned heavily into it in my own tooling, mostly with [this wrapper function](https://github.com/russmatney/ralphie/blob/76fed57cda6e729379318791d5ebc1af0dad202d/src/ralphie/rofi.clj#L17). If this is redundant, feel free to close, just thought I'd throw it up here.
Rofi is a linux modal menu for fuzzy filtering, with a similar UX to Alfred or Spotlight on OSX.
Borrows quite directly from the fzf example.
=> Add rofi example

doc/libraries.md
As suggested on the clojurians slack, adds a link to https://github.com/turtlequeue/setup-babashka
=> feat: add link to turtlequeue/setup-babashka

README.md
Hi,
Just updating the basic install command to work with Linux and OSX. Please, if you agree and want to merge this micro improvements, go ahead. 
Why this change:
At Linux (Ubuntu) when I trying to install with `bash <(curl -s https://raw.githubusercontent.com/babashka/babashka/master/install)` I get: bash: /dev/fd/63: No such file or directory
` <(...)` operator is also known as process substitution and is a way to run command, the output of which goes into the anonymous pipe, in this case: /dev/fd/63. More context can be [found](https://askubuntu.com/questions/678915/whats-the-difference-between-and-in-bash/678919#678919). But maybe is just some issue on my Linux machine, works as it is on Mac.
Thanks
=> Update README install command to work with Linux as well

examples/file-server.clj
* A correct MIME type of a served file is guessed by the file extension.
* For example, SVG images are now displayed correctly in a web browser.
=> Guess and add correct "Content-Type" headers for responses.

.circleci/script/docker, .circleci/script/publish_artifact.clj, .circleci/script/release, install
This PR will allow future releases to be packaged at .tar.gz. This is probably better since many docker containers don't come with `unzip`, but do come with `tar`.
We use a crappy version check (thank you, bash) to see if the version we are downloading is newer than the current (0.2.13), and if so, then use `tar` and a _.tar.gz_ extension.
Make sure to not merge this unless 0.2.14 is ready to be released in tar format!
=> Update install to support future tar.gz releases

install
We were only using this var in the echo, but it always said .zip, even
if we were using .tar.gz
=> install: Use $download_url

examples/notes.clj
I'm also working on rewriting this to use org.httpkit.server as suggested in the comment at the top of the file. But until then, here's a bug fix for the hand-rolled server.
=> Fix cookie-parsing bug in the example note-taking app

src/babashka/main.clj, test/babashka/bb_edn_test.clj, test/babashka/test_utils.clj, test/babashka/uberjar_test.clj
It was previously using the classpath coming from the parameters/env. We need to use
cp/get-classpath for taking into consideration the classpath coming from bb.edn.
=> Use get-classpath when build an uberjar

doc/projects.md
This duplicates the example in [spartan.spec](https://github.com/borkdude/spartan.spec#example), but I figure that in some cases, people will check this list of projects before they think to check the READMEs of individual projects.
=> Adds Expound to projects.md

examples/README.md, examples/is_tty.clj
An equivalent of Python's `os.isatty()` in Babashka, to check if the `stdin`/`stdout`/`stderr` is connected to a TTY or not (useful to check if the script output is being redirect to `/dev/null`, for example).
=> Add `examples/is_tty.clj`

src/babashka/impl/classes.clj
This will enable the creation of zip files via babashka scripts.  
To quote your reply on Slack:
> We already have `GZIPOutputStream` so it's a bit silly that we don't have `ZIP`
😃
=> Add class `java.util.zip.ZipOutputStream`

.circleci/config.yml, Dockerfile, script/compile, script/setup-musl
Based on https://github.com/babashka/pod-babashka-aws/pull/37.
This is the recommended way to build static binaries with GraalVM by the documentation and multiple issues on GitHub. See:
- https://www.graalvm.org/reference-manual/native-image/StaticImages/
- oracle/graal#571 (comment)
The reason that building a statically binary with glibc is complicated is explained in the glib documentation:
https://sourceware.org/glibc/wiki/FAQ#Even_statically_linked_programs_need_some_shared_libraries_which_is_not_acceptable_for_me.__What_can_I_do.3F
=> Build BABASHKA_STATIC with musl C library

script/compile
Just to make sure that we are using the correct source code.
The SHA256 can be double checked in the https://zlib.net/ website.
=> Add sha256sum check to zlib

install
- Add `--checksum` option. This will allow to check the SHA256 sum of the download, making sure that we are downloading the correct binary. By default, there is no check, to keep this script backwards compatible (e.g.: if someone doesn't use `--checksum` option, they don't need to have `sha256sum` installed)
- Add `--static` option. This will, on Linux systems, download the static release instead of the dynamic one. On macOS it exit with error
- Some small refactorings
=> Improve install script

src/babashka/impl/clojure/java/browse.clj
This PR add two improvements to `babashka.impl.clojure.java.browse`, fixing issue https://github.com/babashka/babashka/issues/845.
Binaries in Linux are not guarantee to be located on `/usr/bin`.
For example, NixOS the binaries are located in `/run/current-system/sw/bin/xdg-open` (that is actually just a symlink to `/nix/store`). The distro may also not have `xdg-open` installed at `/`, instead the user may put it somewhere else like `$HOME/bin`.
This commit fixes this by using not hardcoding the PATH of `xdg-open`, instead relying on shell path to search it.
This allows usage of a custom URL script, like:
```clojure
(binding [*open-url-script* (atom "my-browse-url-script")]
(browse-url "https://google.com"))
```
`*open-url-script*` is an atom just to keep compatibility with Clojure. …
=> Improve `clojure.java.browse`

install
`sha256sum` is not available in macOS by default.
See: https://github.com/ESGF/esg-search/issues/84#issuecomment-213694850
However, `shasum` seems to be avaialble, so use that instead.
P.S.: not actually tested at macOS since I don't have one.
=> Use shasum instead of sha256sum

script/setup-musl
I was trying to understand why we needed that hack to copy `libz.a` to the GCC library path even if GraalVM is supposed to set the linker correctly if we had `musl-gcc` at our PATH.
I finally figured the issue. As you can see in the code below, `zlib` sets `libdir` to the directory passed on `--prefix` and appends `/lib`:
https://github.com/madler/zlib/blob/v1.2.11/configure#L76
This would work fine if `/usr/lib` was the expected location for libraries (however the script was still wrong, since `--prefix` would need to be set to `/usr` for it to work correctly), however on Debian each library has the following format depending on the architecture/compiler:
- `/usr/lib/x86_64-linux-musl`
- `/usr/lib/x86_64-linux-gcc`
So passing `/usr/lib/x86_64-linux-musl` to the `--prefix` parameter on …
=> Improve script/setup-musl

install
- Use `mktemp -d` to generate a temporary directory, only if user doesn't use `--download-dir`
- Clean-up the temporary directory using `trap`. Remove other `rm` calls from code since they're not necessary
anymore
- Run download in a subshell, so after finishing it the script is still on the directory where the user ran
the script. Fix `./install --dir .` usage
- Fix backup of old Babashka install
=> Improvements to install script

install
While creating [this gist](https://gist.github.com/thiagokokada/115b2588ff65a48d54b8832488801c92) I realized that exiting if the `--static` flag is passed on non-Linux systems just make more difficult to handle those cases.
Instead, let's just print a message informing the user of their mistake, and keep running the script with the correct filename.
=> Do not exit when --static is called on non-Linux

script/test.bat, test/babashka/main_test.clj, test/babashka/scripts/System.bb, test/babashka/test_utils.clj
A handful of tests are failing on my WSL build, but they also fail when running the tests from master, so it seems like there are some kinks to work out in my WSL testing. It doesn't seem related to these changes, but it might not hurt to let the CI checks run first to make sure Linux/Mac are held harmless by these changes (mainly just the normalize call on `bb-native`).
- add `normalize` call to `bb-native` output
- add `escape-file-paths` function to double up backslashes for Windows paths
passed as strings
- update test.bat to more closely mirror the Linux/Mac test script
The only maybe confusing change IMO is to scripts/System.bb - Windows machines generally use HOMEPATH instead of HOME, so or'ing them should result in non-nil everywhere (as far as I can tell).
=> add more windows testing (#235)

appveyor.yml, project.clj, script/test.bat, test/babashka/async_test.clj, test/babashka/bb_edn_test.clj, test/babashka/classpath_test.clj, test/babashka/deps_test.clj, test/babashka/error_test.clj, test/babashka/impl/clojure/java/shell_test.clj, test/babashka/impl/nrepl_server_test.clj, test/babashka/main_test.clj, test/babashka/test_utils.clj, test/babashka/transit_test.clj, test/babashka/uberjar_test.clj, test/babashka/udp_test.clj
this is kind of a big PR in my mind, so I apologize for that, but a large amount of the change is 'swapping' :windows and :skip-windows
- change from selecting tests to run to selecting tests to skip (remove all :windows tags, add
:skip-windows tag to tests that don't currently work on windows)
- handfuls of calls to `normalize` and `escape-file-paths` to handle platform differences
- split `b.bb-edn-test/task-test` to make most of the tests run on windows, and exclude just a couple of Unix-y tests
I think the difference between Windows tests and Linux tests is now something like 10-15 assertions, but one of the big ones is the pods test, so if it's ok with you, I'd like to take some time and maybe play around with making the pod test work on Windows JVM (it works as a native test). I'd …
=> make tests run on windows as the default (#235)

test/babashka/main_test.clj
following up on your point in #922 about adding some extra tests, this just exercises the other options for the first arg to `cl-format`
=> add cl-format tests for nil and Writer args

appveyor.yml, deps.edn, script/lib_tests/bb_edn_from_deps.clj, script/lib_tests/run_all_libtests, script/lib_tests/run_all_libtests.bat
- add lib-tests path to deps.edn and remove it from shell scripts
- change windows lib test batch script to write a bb.edn file
- re-enable native lib tests on windows
things are working locally, and the main reliance on the windows stuff is environment variables, and not capturing command output
in my local testing, the (native) lib tests run in about 30 seconds, so I don't imagine these will add a ton of time to the build
=> fix windows lib tests (#940)

script/compile.bat, test/babashka/bb_edn_test.clj
It looks like the deps.edn resource that got added to `compile` just needs to get added to `compile.bat` as well. This made the test pass immediately in my local env.
=> add META-INF resource to windows compilation (fixes #963)

src/babashka/impl/clojure/core.clj
- refer to `clojure-core-ns` from `sci.impl.vars` instead of `sci.impl.namespaces` (continuation of borkdude/sci#597)
- add `:ns` meta to core dynamic vars (much like the dynamic vars from `sci.impl.io`)
=> varify some core dynamic vars (#957)

feature-core-async/babashka/impl/async.clj, src/babashka/impl/clojure/core.clj, src/babashka/impl/clojure/java/io.clj, src/babashka/main.clj, test/babashka/impl/clojure/java/io_test.clj
- add `:ns` to `core.async`, `clojure.java.io`, `clojure.main`, and a couple vars from `clojure.core`
- add a couple extra tests for the Coercions protocol methods (to increase confidence that `copy-var` doesn't mess with the multimethod behavior)
Assuming that this and borkdude/sci#604 get merged, my plan is to write one or two tests that basically check that all the vars (minus the `clojure.lang` and `user` namespaces) have `:ns` meta, and that the meta matches the namespace that they're in, to keep any new vars honest.
=> add :ns meta to more vars (#957)

feature-jdbc/babashka/impl/jdbc.clj, feature-test-check/babashka/impl/clojure/test/check.clj, test/babashka/namespace_test.clj
- `quick-check`'s metadata had its ns as `clojure.test.check.properties`, but is in `clojure.test.check`, so change that meta
- add `namespace-test` to test that all the public vars have `:ns` metadata, and that it matches their containing namespace (checking that ns names are equal, not that they're identical, because the features don't currently have identical namespaces)
I would say, at your discretion, this might be sufficient to close out #957 - the only vars that don't have `:ns` in their meta now are the `clojure.lang` ones and `*input*`
=> test that var metadata matches containing ns

deps.edn, doc/projects.md, feature-lanterna/babashka/impl/lanterna.clj, test-resources/lib_tests/babashka/run_all_libtests.clj, test-resources/lib_tests/multigrep/core_test.clj, test-resources/lib_tests/multigrep/haiku.txt
this change also corrects the name of the `lanterna.constants` namespace
=> add lib test and an example for multigrep (#461)

script/setup-musl
Now that bullseye was released, Debian is starting to make bigger changes on unstable. To avoid breakage, let's use musl from bullseye that is the correct version that we were using until now (1.22-1): https://packages.debian.org/bullseye/musl-tools
Eventually a better solution would be to simply use Debian bullseye to compile everything, however the official Clojure image from Docker is still using stretch. So this is a temporary solution until them.
Fix issue: https://github.com/babashka/babashka/pull/972
=> script: use musl from bullseye instead of unstable

src/babashka/main.clj, test/babashka/main_test.clj
just adding `:default` to all the places where we use `edn/read` to populate `*input*`
=> use tagged-literal for unknown EDN tags when creating *input* (#975)

src/babashka/impl/classes.clj
PR for size comparison. (Locally it checks in at 87M, compared with 83M without the new classes)
Still some open issues:
I'd also like to add a helper function to handle requests with input-stream bodies along the lines of the following:
```clojure
(ns babashka.http-helper
(:import
(java.util.function Supplier)))
(defn input-stream-supplier [^java.io.InputStream is] (reify Supplier (get [_] is)))
```
=> Add classes to support JDK-11 java.net.http

src/babashka/impl/classes.clj, src/babashka/impl/reify.clj, test/babashka/java_http_client_test.clj
Sadly, no tests.
hato uses httpkit.server for [testing WebSockets](https://github.com/gnarroway/hato/blob/master/test/hato/websocket_test.clj#L21) , but the implementation in Babashka doesn't include the `org.httpkit.server/with-channel`. Looking at using `as-channel` instead.
I believe this includes all of the implementation classes needed (i.e., `jdk.internal.net.http.websocket.BuilderImpl`), but I haven't confirmed it.
=> Add WebSocket support.

README.md
Finding myself scrolling around the readme for some seconds trying to find the link to the docs, which is a couple of sections down from the top. In order to help people (and myself) to find the reference faster, I added a badge in the top that links to the book/docs.
=> Add docs badge to top of README

.circleci/config.yml, .dockerignore, Dockerfile, script/download-graalvm, script/install-clojure, script/install-graalvm, script/setup-musl
Fix issue #866.
Also, many QoL changes on `Dockerfile`/`.cicleci/config.yml`.
=> Use Debian bullseye on CI/CD/Dockerfile

src/babashka/impl/clojure/core.clj, src/babashka/main.clj, test/babashka/xml_test.clj, test/babashka/yaml_test.clj
Should close #1004 .
- On Clojure-JVM, `clojure.core/*data-readers*` has an initial value of an empty map. This change facilitates using `into` later on when we populate `*data-readers*` for 'runtime'.
- conditionally add the `clojure.data.xml` data readers to edn-readers
- the value of edn-readers mostly reflects what `*data-readers*` would be when starting Clojure-JVM with the YAML and XML deps, so we dump edn-readers into `*data-readers*` to emulate the handling of data_readers.clj (it's missing `ordered/set`, but I don't think that's needed for the YAML feature).
- add XML and YAML round-trip testing, both between bb invocations (to emulate piping and exercise edn reading to `*input*`) and within one bb process (to exercise `*data-readers*` usage)
=> XML edn reading and populating *data-readers* for feature deps

src/babashka/impl/classes.clj
java.util.stream.BaseStream was included in public-classes but not classes itself, which prevented it from being imported:
Before
```
./bb -e "(import 'java.util.stream.BaseStream)"
----- Error --------------------------------------------------------------------
Type:     java.lang.Exception
Message:  Unable to resolve classname: java.util.stream.BaseStream
Location: <expr>:1:1
----- Context ------------------------------------------------------------------
1: (import 'java.util.stream.BaseStream)
^--- Unable to resolve classname: java.util.stream.BaseStream
----- Stack trace --------------------------------------------------------------
user - <expr>:1:1
```
After:
```
% ./bb -e "(import 'java.util.stream.BaseStream)"
java.util.stream.BaseStream
```
If you'd like tests, I'll look into …
=> Include java.util.stream.BaseStream in classes.

src/babashka/impl/classes.clj
fixes #1046 
The pg driver appears to use reflection to check annotations on fields. This change will make those fields available.
The executable sizes produced by my build process are a) not in the "reference context" for size and b) not amazingly consistent, but as far as I can tell:
- when postgres flag is false, the executable size with the change is about 1KB larger than without the change
- when postgres flag is true, the executable seems to consistently be smaller by 100KB - 1MB with the change than it is without the change (I don't understand that, but it seems to work out that way on Windows)
Regarding functional testing, I was able to use the postgresql-test class with `BABASHKA_TEST_ENV=native` (with removing the `tu/jvm?` condition) in …
=> add PGProperty fields (conditionally) to reflection config

src/babashka/impl/classes.clj, test/babashka/crypto_test.clj
Used by was-api:
https://github.com/cognitect-labs/aws-api/blob/master/src/cognitect/aws/util.clj#L96-L100
Perhaps there's an alternative method to do this calculation with what's already in babashka. I haven't looked, and it's not an area I'm familiar with.
=> Add javax.crypto classes necessary for calculating hmac shas.

install
Created on behalf of @Cnly
Fixes #1085
=> Force decimal version numbers in install script

Dockerfile, script/setup-musl
Issue:
https://github.com/babashka/babashka/issues/1096
This will now default to building an image for the platform your Docker daemon is running on, but you can override it with the `--platform` arg to `docker buildx build`.
`TARGETARCH` build arg is documented here: https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in-the-global-scope.
Note that the multi-platform support requires using the [BuildKit backend in Docker](https://github.com/docker/buildx) which should be the default in recent versions of Docker.
=> Allow building x86_64 or arm64 Docker images

test-resources/lib_tests/clojure/data/json_test.clj, test-resources/lib_tests/table/core_test.clj
This just tweaks the line endings in the test comparisons for a couple of tests, in order to eliminate the Appveyor failures.
=> handle system-specific newlines in a couple of tests

examples/http-server.clj
Fix a URL in a comment to account for a moved file. None of the following template to-dos appear to be relevant to this one-byte typo fix, but let me know if you disagree:
=> Fix broken link to source in comment

CHANGELOG.md, Dockerfile, project.clj, script/compile, script/uberjar
From clojurians slack: https://clojurians.slack.com/archives/CLX41ASCS/p1641396669154300
> I've been playing around with a lein plugin that generates what I'm calling a meta-bom-jar, that basically just contains the group, artifact and version of all a project's dependencies (https://github.com/kipz/lein-meta-bom). If we included this in the babashka Docker images, we could give vulnerability scanners visibility into the bill of materials in use by uberjars, graal native images and so on. I tried on a fork https://github.com/kipz/babashka/tree/metabom and it seems to work (in that grype can now see all the packages in the babashka images).
=> Add bill-of-materials to Docker images to aid vulnerability scanning

.circleci/script/docker, CHANGELOG.md
Adds  opencontainers annotations to the docker image via the circle-ci build for traceability as per:
https://github.com/opencontainers/image-spec/blob/main/annotations.md
I was unable to test this fully of course!
=> Add opencontainers annotations to docker image

.circleci/script/docker
Follow up to #1141 that makes alpine tagging and pushing consistent with other variants
=> Fix: alpine docker builds in CI (follow-up)

src/babashka/main.clj, test/babashka/main_test.clj
Permits previously-accepted behavior broken in 19415f63632d2fe8f668fa82ea91c80d06666292
Fixes https://github.com/babashka/babashka/issues/1143
Nope. Not yet.
The added test for `--` as the next arg is simple and works but likely there's a more elegant/idiomatic solution.
=> Allow optional (ignored) -- when using using --main

CHANGELOG.md, src/babashka/main.clj, test-resources/babashka/config_property.clj, test/babashka/main_test.clj, test/babashka/test_utils.clj
There's something curious going on with the tests: 
```bash
> lein test :only babashka.main-test
[...]
Ran 90 tests containing 202 assertions.
0 failures, 0 errors.
```
when running all tests however:
```bash
> lein test
[...]
lein test :only babashka.main-test/config-property-test
FAIL in (config-property-test) (main_test.clj:607)
expected: (= "false\n" (test-utils/bb nil (.getPath (io/file "test-resources" "babashka" "config_property.clj"))))
actual: (not (= "false\n" "true\ntrue\n"))
[...]
Ran 189 tests containing 563 assertions.
1 failures, 0 errors.
Tests failed.
```
I've poked at it a little bit, and it appears that the generated bb.edn file from a previous test case gets picked up, changing the behaviour. A smaller repro is to reverse the order of test clauses in …
=> add `babashka.config` property

src/babashka/impl/classes.clj
Deflater allows one to control, for example, the level of compression
used. The DeflaterOutputStream is the parent of GZIPOutputStream
class, and allows raw zlib compressed stream (i.e. no gzip header/footer).
=> Add Deflater and DeflaterOutputStream

script/setup-musl
The newer 1.2.12 version is breaking the tests. The older version is not
available in the main download path, however it is still available in
the archive.
=> Unbump zlib to version 1.2.11

CHANGELOG.md, src/babashka/main.clj, test/babashka/bb_edn_test.clj
Improves the error message by informing the user that literal regex syntax is not allowed and recommends using re-pattern instead.
=> Improve error message when regex literal in EDN config (#1041)

CHANGELOG.md, src/babashka/main.clj
Downloads deps & pods, caches pod metadata, and then exits
=> Add prepare subcommand

CHANGELOG.md, feature-hiccup/babashka/impl/hiccup.clj, feature-httpkit-client/babashka/impl/httpkit_client.clj, src/babashka/impl/clojure/core/async.clj, src/babashka/impl/clojure/test.clj, src/babashka/impl/deps.clj, src/babashka/impl/tasks.clj, test-resources/babashka/check_var_names.bb, test/babashka/main_test.clj, test/babashka/scripts/check_var_names.bb
Closes #1223 (to be clear, most of #1223 was done in https://github.com/babashka/sci/pull/710; this just makes a handful of var names be the "expected" names)
This is primarily just a set of little changes to align the var name metadata for copied vars that have a different target name. Additionally, there's a new test that runs a script that checks `(ns-publics)` namespace name and symbol against the corresponding var's metadata and returns any mismatches (and obviously, the test fails if there are any mismatches). Caveat: that test does skip `*input*` because getting to its metadata is... shall we say, not as straightforward as using ns-publics.
before:
```
>bb "(doc hiccup.core/html)"
-------------------------
hiccup.core/html-1
([options & content])
Macro
Render Clojure data...
``` …
=> update some SciVar names (metadata-wise) to align with babashka name

feature-httpkit-server/babashka/impl/httpkit_server.clj
This function has been forgotten to be copied to the namespace, as `server-port` already is. 
=> [#556] Add server-status to org.httpkit.server

deps.edn, project.clj, reify/build.clj, reify/src/babashka/impl/reify2/interfaces.clj, resources/META-INF/babashka/deps.edn, src/babashka/impl/classes.clj
See https://github.com/mpenet/auspex
```
$ bb -cp $(cat .classpath):test -e "(require '[qbits.auspex-test]) (clojure.test/run-tests 'qbits.auspex-test)"
Testing qbits.auspex-test
Ran 11 tests containing 74 assertions.
0 failures, 0 errors.
{:test 11, :pass 74, :fail 0, :error 0, :type :summary}
```
=> auspex compatibility

src/babashka/impl/pods.clj, src/babashka/main.clj
Companion PR for https://github.com/babashka/pods/pull/53 that sets the `:download-only` flag when os.name / os.arch don't match what was requested via env vars.
=> Only download pods when os.name / os.arch don't match the system

src/babashka/impl/classes.clj
I'm not sure what kinds of considerations there are related to adding support for classes, but the implementations of these classes is very small, and I think it makes sense to support them since `ThreadPoolExecutor` is already supported.
=> Add ThreadPoolExecutor rejection policy classes

src/babashka/main.clj
This fixes the test failures from the https://github.com/babashka/pods/pull/53 merge. That PR should be OK to re-merge now.
=> Fix download-only? fn & use new env var names

src/babashka/impl/classes.clj
Didn't quite catch all of them the first time around. :)
Adding these doesn't seem to have any appreciable effect on the binary size, either:
```bash
λ ls -lat bb
-rwxr-xr-x  1 eerohe  staff  72574720 Sep  9 21:38 bb*
```
(These are necessary for implementing auto-completion for Java class methods.)
=> Add more reflection class methods

src/babashka/impl/classes.clj, src/babashka/main.clj, test/babashka/classes_test.clj
To offer editor auto-completion for the Java classes Babashka supports, we need to expose a list of those classes to users.
Question: should `all-classes` return a list of `java.lang.Class` instances (as in this PR), or a list of symbols?
Maybe it should? Any thoughts on how you'd like to have this tested? Testing is somewhat complicated by the fact that not all class names (e.g. `[Ljava.time.temporal.TemporalField;`) are read-able.
=> Add and expose babashka.classes/all-classes

CHANGELOG.md, src/babashka/main.clj, test/babashka/main_test.clj
Closes #1336 
This change moves `--force` from opt parsing to global opt parsing.
I was initially worried about regressions from removing force as an option, but based on some cursory arg parsing testing on master, it looked like (in addition to the issue reported), `--force` often either doesn't set `:force?`, or causes commands that come after it to be treated as a file name (the reported issue is one case of this).
=> Force as global opt

src/babashka/impl/deps.clj
this should address the empty map supplied as `:deps` as discussed on this Slack [thread](https://clojurians.slack.com/archives/CLX41ASCS/p1664199604550759)
=> check if supplied deps is non-empty

src/babashka/main.clj
This improves the error visibilty when loading a `bb.edn` by marking the it better instead of just the stacktrace which could be confusing.
=> Mark bb.edn load exception

CHANGELOG.md, src/babashka/impl/pprint.clj, test/babashka/pprint_test.clj
We can now use the dynamic var `*print-namespace-maps*` to control how maps with namespaced keys are printed using `pprint`.
Fixes: #1381
=> feat: Honor `*print-namespace-maps*` in pprint

README.md
In the `Pods` section we were pointing to a place with a slightly outdated list of projects. This patch adds the correct link to the pod registry.
=> Link pod registry to Pods section in README

Dockerfile.alpine
Alpine 3.16 includes /etc/nsswitch.conf, which glibc install tries to create. This change adds the force-overwrite flag to the glibc install.
=> add force overwrite flag when installing glibc on alpine (docker)

CHANGELOG.md, src/babashka/impl/tasks.clj, test/babashka/bb_edn_test.clj, test/babashka/impl/tasks_test.clj
Hi,
can you please consider patch to fix issue with `bb tasks`ing with an empty tasks display list. Fixes #1430 
The logic now considers the reduced list when printing out the tasks list.
=> Fix issue with empty tasks names display list

CHANGELOG.md, src/babashka/impl/classes.clj, test/babashka/java_time_test.clj
I saw that juxt/tick almost has babashka support and decided to look into getting it working. You left a comment here:
https://github.com/juxt/tick/issues/86#issuecomment-646804841
indicating you would welcome PRs adding missing java.time classes so I didn't create an issue a I thought it was clear from that comment one wasn't needed.
The remaining missing classes are all related to date formatting.
This [fork](https://github.com/dvingo/tick/tree/babashka-update
) of juxt/tick has the tests passing in bb against the version of Babashka build off of the branch for this PR.
=> Add more java classes and interfaces to support juxt.tick

CHANGELOG.md, src/babashka/main.clj, test/babashka/main_test.clj, test/babashka/uberjar_test.clj
closes #1489 
Summary of changes:
- `file-write-allowed?` checks that the file is a jar or empty/non-existent
- before writing uberjar or uberscript, check that file write is permitted (for uberjar specifically, I tweaked the classpath check into a cond instead of nesting ifs)
- add tests that check:
- uberscript doesn't overwrite non-empty target
- uberjar does overwrite non-empty jar
- uberjar doesn't overwrite non-empty file other than jar (simulating a source file being specified)
We can definitely change the 'overwrite prohibited' message if there's different wording you'd prefer.
=> Prevent uberscript/uberjar overwrites

src/babashka/main.clj, test-resources/lib_tests/hato/client_test.clj, test/babashka/main_test.clj, test/babashka/uberscript_test.clj
This is just the cleanup coming out of #1503 
- babashka.main: don't overwrite any existing non-jar files (including empty)
- babashka.main-test:
-  where needed, delete the temp output files that would otherwise prevent overwrite
- since files no longer to be non-empty, remove the writes
- uberscript-test: delete the temp output files that would otherwise prevent overwrite
- hato.client-test: use httpbin for `test-http2`; httpbin uses http/2, and switching to httpbin aligns with the flakiness check
=> prevent overwrite of empty uber-* target files

CHANGELOG.md, Dockerfile, Dockerfile.alpine, Dockerfile.ci
By removing the package list we could reduce the Docker image size even further from 217MB to 174MB.
=> fix(docker): make image smaller

test/babashka/bb_edn_test.clj
Could close #1189 - adds a test that checks bits of the error message.
This test checks just the message content coming from the JVM, because the lower-level messages differ between OSes, e.g.
- `CreateProcess error=267, The directory name is invalid` on Windows, vs
- `error=2, No such file or directory`  on my linux machine
=> add test for error message for clojure {:dir "missing-directory"}

CHANGELOG.md, src/babashka/impl/classes.clj, src/babashka/impl/features.clj
Exposed GraalVM `ProcessProperties/exec` signature used by babashka.process/exec.
Add new `graal?` feature (on by default) to allow folks to build/use babashka without this specific Graal API.
On my linux dev box bb executable increased by 8kb.
Closes #1557
=> Support babashka.process reload for exec fn

test-resources/lib_tests/babashka/run_all_libtests.clj
Now that babashka.process tests are os agnostic we can also run them on Windows.
This should now work, see babashka/process#126
=> tests: run babashka.process lib tests on windows

README.md
Maybe I'm missing something, but I think the `.clj` file cannot be started without `bb` as the command name.
---
=> Fix README.md prepending the command with bb

deps.edn, project.clj, test-resources/lib_tests/selmer/core_test.clj
No, but we discussed it on the slack, I'm simply bumping Selmer version so it has access to the new resolve-arg fn from selmer.parser.
No, not sure we need one just for a version bump?
Wasn't sure where to add it, in the Unreleased section?
=> Bumping selmer version to 1.12.59

src/babashka/impl/classes.clj
Please consider adding this class to bb.
I'm looking to implement ansible-vault decryption in babashka and I need the above class. 
Decryption works in Clojure but fails with missing class for babashka. 
After this I need to fix crypto padding and all is good :). 
https://docs.ansible.com/ansible/latest/vault_guide/vault_using_encrypted_content.html#format-of-files-encrypted-with-ansible-vault .
(I've read the lines bellow and I'll think of a test for this tomorrow). 
=> Include IvParameterSpec so we can have ansible-vault-clj decryption

src/babashka/deps.clj
Per [Slack](https://clojurians.slack.com/archives/CLX41ASCS/p1707224925015389?thread_ts=1707224870.345309&cid=CLX41ASCS):
> The official way of calling `clojure` is now:
> `(clojure {opts} ..args)`
- can do if needed, but the problem statement is at the top of this PR
- doc update only
- will do
=> Update clojure example to new calling convention

README.md
This PR adds note on asdf performance, suggests mise instead, and adds mise installation instructions.
It seems like a shame when so much work has been put into getting bb to start in 20 ms that asdf adds 120-150 ms. And this is not obvious behavior, new bb users will probably just draw the conclusion that bb is very slow to startup instead of suspecting the real culprit, so I think documenting this is warranted.
Sources, the first is from asdf maintainer stating 150 ms for exec, the latter is mise stating 120 ms:
https://stratus3d.com/blog/2022/08/11/asdf-performance/
https://mise.jdx.dev/dev-tools/comparison-to-asdf.html#performance
=> Suggest using mise instead of asdf

CHANGELOG.md, src/babashka/main.clj, test/babashka/main_test.clj
This change is intended to address a couple of issues described in #1695 
Scenario 4 from the issue:
```
$ bb repl -- asdf sdf <<< '*command-line-args*'
----- Error --------------------------------------------------------------------
Type:     java.lang.Exception
Message:  File does not exist: asdf
```
**Problem Statement**
`--` does not cause args to stop being processed as bb arguments if it comes after `repl` or `--repl` in the arg list
**Root Cause**
`--repl` consumes two arguments from the arg list
**Fix**
main.clj, line 616: recur with `options` (which has already had `--repl` removed)
**Tests**
Added a test for this combination of args
Scenario 3 from the issue:
```
$ bb -- asdf sdf <<< '*command-line-args*'
nil
```
**Problem Statement**
the value of `*command-line-args*` is `nil` …
=> make CLI args available to REPL

CHANGELOG.md, src/babashka/main.clj, test/babashka/main_test.clj
**Problem Statement**
Certain `bb` options (version, help, describe) definitely don't need to fetch dependencies listed in `bb.edn`. When `bb` is invoked with one of these 'fast-path' options and there are deps in `bb.edn`, deps are fetched (and java is called), even though it's not strictly necessary.
**Current State**
`main/exec` always adds deps before it acts on the presence of the fast-path options.
**Change Description**
- The handling of these options gets pulled out to a new function, `exec-without-deps`
- before `exec` gets called, check if any of the fast-path options are present, and if so, call `exec-without-deps` instead of `exec`
**Possible future work**
Since the issue at hand was focused on execution of java (for fetching deps), I only moved the commands that definitely …
=> Fix #1686: do not fetch deps/invoke java when deps aren't needed

CHANGELOG.md, src/babashka/main.clj, test/babashka/bb_edn_test.clj
**Change Description**
- catch exceptions when resolving symlinks during `babashka.main/main`
**Tests**
- Since the failing scenario is somewhat esoteric, and getting predictable ephemeral files was a bit tricky with JVM testing, the test only runs on native, non-windows builds. The test feels like a pretty faithful repro of #1700 (failed with the same exception prior to the change).
=> Fix #1700: catch exceptions from resolving symbolic links during `bb.edn` lookup

script/lib_tests/run_all_libtests, script/lib_tests/run_all_libtests.bat
Default `BABASHKA_TEST_ENV` to `jvm` for libtests
CI already understands this need, but defaulting in-script avoids having devs to understand/remember it too.
Alter PATH as required for new babashka.process tests.
In support of babashka/process#163, babashka/process#164
=> Support running of new babashka.process tests

doc/dev.md
The example I provided implied that the set applied only to the next command. I've learned that this is not the case.
Also: mention what shell examples apply to.
=> docs: dev: windows set example misleading

doc/dev.md
Sort of: I wrote it because I ran into this issue when contributing here: https://github.com/babashka/http-client/issues/73
No, it's documentation-only
Since it's documentation-only this does not seem worth it?
=> Document that tests should prefer to hit public APIs

CHANGELOG.md, src/babashka/impl/classes.clj
java.net.http.HttpClient, included in Babashka, can throw java.lang.SecurityException
https://docs.oracle.com/en/java/javase/11/docs/api/java.net.http/java/net/http/HttpClient.html
Intended in support of https://github.com/babashka/babashka/issues/1752
If this feature is desired, feel free to disregard these PRs and include it directly. I've typo'd the first commit message, and the commits should likely be squashed into one anyway.
I looked to see if other exception inclusions contain a test and didn't find any. Happy to include a trivial test if that helps move this forward.
=> Include java.lang.SecurityException

README.md
Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [Babashka Guru](https://gurubase.io/g/babashka) to Gurubase. Babashka Guru uses the data from this repo and data from the [docs](https://book.babashka.org) to answer questions by leveraging the LLM.
In this PR, I showcased the "Babashka Guru", which highlights that Babashka now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.
Additionally, if you …
=> Introducing Babashka Guru on Gurubase.io

CHANGELOG.md, src/babashka/impl/classes.clj, test/babashka/interop_test.clj
Apart from the addition of `Throwable`, the added tests are aimed at covering a couple of the resolutions. So, there's no app code change that's applicable to `Charset` or `InputStream`, but I wanted to cover a few of the superclasses so that if a regression comes up in the future, it might be more evident whether it's an individual superclass that's impacted, or the whole `:public-class` fn.
=> allow subclasses of Throwable to have instance methods called via interop

CHANGELOG.md, README.md, install
Closes #1815 
Verify with e.g.:
```
$ docker run -it ubuntu:latest bash -c 'apt-get update && apt-get -y install wget && bash < <(wget -qO- https://raw.githubusercontent.com/eval/babashka/refs/heads/install-supports-wget/install) && bb version'
```
=> Make install-script wget-compatible
